### ISSUE TITLE
Creating caffe model

### ISSUE THREAD

**Issue by samsgates** [anhttran/3dmm_cnn#11]
how to create my own caffe model using full head model. i have unique 50 full head model with input picture (PNG image) for creating model. 
i am new for caffe network model, can you please guide me to create caffe model which is support your CNN system.

Sample model:
<img width="499" alt="head" src="https://user-images.githubusercontent.com/4558944/27249726-d79c8fe0-5339-11e7-9656-4c9b1cbddbf0.png">

**Comment by anhttran** [comment]
I am sorry that I can answer you only now. I have been busy under a tight deadline.
In our work, we use 3DMM for 3D face model representation: each 3D face corresponds to a vector of 198 shape+texture parameters. The CNN just regresses this vector instead of the entire 3D model; it is simpler and more convenient.
3DMM consists of the mean face and principal components. To define your own 3DMM, you can refer to Basel Face Model paper:
"A 3D Face Model for Pose and Illumination Invariant Face Recognition", P. Paysan, R. Knothe, B. Amberg, S. Romdhani, and T. Vetter, AVSS 2009.
