### ISSUE TITLE
Provide links for model files download

### ISSUE THREAD

**Issue by yashiro32** [anhttran/3dmm_cnn#27]
Hi, can you provide links to download Model_Expression.mat, BaselFaceModel_mod.mat and BaselFaceModel_mod.h5. Not everyone have Matlab.

**Comment by iacopomasi** [comment]
Hi @yashiro32 ,
it is indeed true that not everyone has MATLAB but it is also hard for us to package all the necessary data and library in a single package mainly due to conflicting license or licenses that do not allow us to do that.

Anyway, remember that you can still open [`.mat` with python](http://www.blogforbrains.com/blog/2014/9/6/loading-matlab-mat-data-in-python).

I hope this helps.

**Comment by anhttran** [comment]
Due to licensing issue, we cannot provide you those files directly.

Model_Expression.mat is generated by 3DDFA code. You can try an alternative of Matlab, such as Octave, to run their code. Otherwise, you can convert their code to Python; it should not be hard (see our code trimBaselFace.py as an example).

BaselFaceModel_mod.* can be generated after that purely with our Python code (trimBaselFace.py).

Best,
Anh
