### ISSUE TITLE
A question about experiments

### ISSUE THREAD

**Issue by MariaWang96** [anhttran/3dmm_cnn#58]
Hi! Thanks for your great work in 3D face reconstruction!

I have a question about the processing of MICC Florence dataset.

How did you process the scan results, especially the crop step?  Because I find it difficult to find the nose point accurately T_T...

**Comment by anhttran** [comment]
Dear,

The evaluation code is very messy and was never prepared for public release. I uploaded some parts of my code & I hope you find them useful: [https://drive.google.com/drive/folders/1KbkaDBkopkPI_eyFJstLaPWhyIQVFwJC](https://drive.google.com/drive/folders/1KbkaDBkopkPI_eyFJstLaPWhyIQVFwJC)

** Precisely, we did not use the ground-truth models as is. Instead, we aligned the ground-truth models and cropped them. You can find the ground-truth models we used in **AlignedModels.zip**. 
You can see that each subject has 3 models:
- XX.obj:  the aligned model
- XX_n.obj: the aligned model with normals
- XX_crop.ply: the cropped model 

** Matlab code: **matlab_code.zip**
The main file is **compareModelCNN_MICC.m**
It calls 3 external programs to do ICP alignment, to compute 3D-RMSE, and to compute depth-based error measures.

** Visual C++ code: **Match3D.zip**
- ICP alignment: use **icp.cpp**
- 3D-RMSE computation: use **compareModels.cpp**

** The code for depth-based error measures is a bit complicated since it requires rendering. You can find a code segment in **depth_based_pseudo.txt**.

Best regards,
Anh

**Comment by heyoon01** [comment]
Hi! Thanks for sharing your evaluation code. I find them very useful.
I have one question though.
Since ICP algorithm performs rigid transformation with no scaling factors,
scaling the mesh seems important before performing registration.
However, the resulting meshes (of different researches) that needs to be evaluated, 
are aligned with the input facial images, which are all cropped with different method for each works.
So my question is, how do you scale the mesh for each work?
I wonder how XX_n.obj are aligned with, in order to use it as the baseline for aligning other works.
